services:
  backend:
    image: tsu.vizit.application
    build:
      context: .
      dockerfile: TSU.Vizit.Application/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=postgres;Password=iRboe8Jqm4;Database=vizit
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - app-network
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iRboe8Jqm4
      POSTGRES_DB: vizit
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
